dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: WA/RZ2vNLaTHghGzdK6owTv6y5yzMLzAW1KGags+CjUlCrklYN2hulEXXby25w65zU6T4ILpw4DZl8QEjWVXCnza5nbNx6MdIbF2lGRN2bOJ0dwj/xPPxSZWMBLsPljZ5WcmLwA8bMPWYmaZ4AVoqCkjbEYVmDY5gvXCKlqofjP5GvUJunInp37D8CbBkCDntd2nkr1MbvNwi2iZTlW3pdOQ+a4y9iLpuv50NFdJm0kgDaGj0T/vTaVfeKJz1ddFemYHMxfnxXPFi6sTz3c4aQysMcNSCHuow5FAYwkb2+2jNL02OFVjOYizLhjA9NP7qII3oraFQuiBG0KuCdSCHc88bFP4e5hjUTDoVkl5jKjWWvJwp92yiSteWepTJ9LJ8c2ldKxOac4FQ0LNwPashItWQlEcGMfC5t/RrkzvZN4OiCtNQ4HryJIMVy4ekuM1LYJdQotA3gn0X6UabLYzEQuQKiiiRB9UWj8vNNY5YG0jhOF4XvSWii82V7gLtMJ2wf76QgL61Z8uLNsi8LtQP+c9WNtvqdlYHjZK6QONHJmXgr68MKF7sjsZby6Ea/V20rFDqrFIDTlwiJhUYUsWqm2wHXqoQf+b+hzfvGjOmfqDisX9a61RByj1mnq55jqWq/hl7dRrMgfSpnn9nPh6aEpAj+LRkCPGY9Dlmm46M6A=
